# Generated by Django 4.0.6 on 2022-07-20 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.PositiveIntegerField(default=0, verbose_name='айди в таблице')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='заказ №')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='стоимость,$')),
                ('delivery_time', models.DateField(default=django.utils.timezone.now, verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Строчка таблицы google',
                'verbose_name_plural': 'Строчки таблицы google',
            },
        ),
    ]
