# Generated by Django 4.0.6 on 2022-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrow',
            name='cost_in_rur',
            field=models.PositiveIntegerField(default=0, verbose_name='стоимость в рублях'),
        ),
    ]
