# Generated by Django 4.0.6 on 2022-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0002_sheetrow_cost_in_rur'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrow',
            name='informed_about_rancid',
            field=models.BooleanField(default=False, verbose_name='Проинформарован о том, что заказ протух'),
        ),
    ]
